### ISSUE TITLE
Files app integration of hosts fails

### ISSUE THREAD

**Issue by rayanamal** [blinksh/blink#1673]
I updated Blink to version 16.0.4.644 and Files app integration is broken. When I tap the Blink location in Locations in Files app:

![C38F82BA-74C6-4F80-A42F-CBFFB3334969](https://user-images.githubusercontent.com/105531105/212360620-f21adc16-970f-496d-811e-a2791be61f06.jpeg)

When I click the three dots seen on the screenshot, a sharesheet titled "NSFileProviderRootContainerItemIdentifier" appears.

I'm on iOS 15.5 with an iPhone 7.

I guess this bug is due to iOS 16 code, as I didn't see any other bug reports (most people moved to iOS16.). I use Blink daily, I'd be glad if this bug is taken care of.

**Comment by carloscabanero** [comment]
This should have been fully fixed in latest TF (721). The File provider should now be able to restart itself in these rare scenarios. Unfortunately, this is just a patch and not a final solution. This should be really rare, and we don't think this extension has that many users. Please vote on #1717 so we know how urgent this is for everyone.

Thanks!

**Comment by rayanamal** [comment]
What do you mean by TF? In my iOS 15 iPad, it's not fixed and I can't see
an upgrade for Blink shell. Files app extension is better in terms of ease
of use than installing a separate SFTP client app, not to mention many of
those apps are not free, or don't have Files integration and their UI is
clunky, or are read-only etc. IMHO.

**Comment by carloscabanero** [comment]
It is on TestFlight. We are testing it out and should be released to public soon. If you are not part of TestFlight please sign up here at community.blink.sh, and write us an email from to hello at blink.sh. I can give you access so you can try it and can confirm from your side.
