### ISSUE TITLE
Blink (iOS12) ssh hang when connecting and mosh not working (related?)

### ISSUE THREAD

**Issue by Iguana9999phil** [blinksh/blink#610]
Bought Blink as I want to use mosh to admin my Ubuntu servers. Started with importing my ssh keys from prompt 2, set up my server and tried to use mosh. Didn’t work. Tried SSH but it hangs until I press the enter key, after that it shows the prompt.
Removed Blink and redid the servers etc, even just adding nothing and use a pure ssh it hangs.

I think this also gives problems with mosh as the keys cannot be exchanged. Running mosh-server manual on Ubuntu and doing an mosh —key= gives an good connection. As mosh-server is not daemonized i’m unable to use Blink. 

Ssh via Prompt2 works as always, ssh and mosh via Termius is also working as expected.

Debugging ssh with -vv and following shows:

ssh -v user@server
socket_callback_connected: Socket connection callback: 1 (0)
ssh_client_connection_callback: SSH server banner: SSH-2.0-OpenSSH_7.6p1 Ubuntu-4
ssh_analyze_banner: Analyzing banner: SSH-2.0-OpenSSH_7.6p1 Ubuntu-4
ssh_analyze_banner: We are talking to an OpenSSH client version: 7.6 (70600)
blink: setting socket keepalive: 1
ssh_userauth_request_service: Failed to request "ssh-userauth" service
ssh_userauth_request_service: Failed to request "ssh-userauth" service
ssh_userauth_request_service: Failed to request "ssh-userauth" service
ssh_userauth_request_service: Failed to request "ssh-userauth" service
ssh_packet_userauth_failure: Access denied. Authentication that can continue: publickey,password
blink: import key id_rsa
ssh_packet_userauth_failure: Access denied. Authentication that can continue: publickey,password
Password:
blink: open channels
blink: open session
ssh_packet_process: Couldn't do anything with packet type 80

**Comment by yury** [comment]
Hi @Iguana9999phil,

Can I invite you TF? We have new version with ton of ssh and mosh fixes. I want to be sure that release version will work for you.

**Comment by Iguana9999phil** [comment]
Yes would be good.

**Comment by yury** [comment]
Ping me at yury.korolev@gmail.com - I will send you invite

**Comment by yury** [comment]
Sent you invite

**Comment by Iguana9999phil** [comment]
Thanks, downloading now and will test asap.

**Comment by Iguana9999phil** [comment]
Tested and still got issues, that i need to enter or press space to end in the ssh session prompt (also tested ssh -vv user@server.domain,com and with password auth) 
ssh2 works as expected and let me end at the prompt.
ssh -vv shows this:

ssh -vv server.domain.com
ssh_connect: libssh 0.8.3 (c) 2003-2018 Aris Adamantiadis, Andreas Schneider and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
ssh_connect: Socket connecting, now waiting for the callbacks to work
socket_callback_connected: Socket connection callback: 1 (0)
ssh_client_connection_callback: SSH server banner: SSH-2.0-OpenSSH_7.6p1 Ubuntu-4
ssh_analyze_banner: Analyzing banner: SSH-2.0-OpenSSH_7.6p1 Ubuntu-4
ssh_analyze_banner: We are talking to an OpenSSH client version: 7.6 (70600)
ssh_kex_select_methods: Negotiated curve25519-sha256,ssh-ed25519,aes256-ctr,aes256-ctr,hmac-sha2-256,hmac-sha2-256,zlib@openssh.com,zlib@openssh.com,,
ssh_packet_dh_reply: Received SSH_KEXDH_REPLY
ssh_client_curve25519_reply: SSH_MSG_NEWKEYS sent
ssh_packet_newkeys: Received SSH_MSG_NEWKEYS
ssh_packet_newkeys: Signature verified and valid
blink: setting socket keepalive: 1
ssh_userauth_request_service: Failed to request "ssh-userauth" service
ssh_userauth_request_service: Failed to request "ssh-userauth" service
ssh_userauth_request_service: Failed to request "ssh-userauth" service
ssh_userauth_request_service: Failed to request "ssh-userauth" service
ssh_packet_userauth_failure: Access denied for 'none'. Authentication that can continue: publickey,password
ssh_packet_userauth_failure: Access denied for 'none'. Authentication that can continue: publickey,password
blink: using auth methods attempt: 1 of 5
blink: import key id_rsa
ssh_pki_import_privkey_base64: Trying to decode privkey passphrase=false
blink: open channels
blink: open session
channel_open: Creating a channel 43 with 2097152 window and 32768 max packet
ssh_packet_global_request: Received SSH_MSG_GLOBAL_REQUEST packet
ssh_packet_global_request: UNKNOWN SSH_MSG_GLOBAL_REQUEST hostkeys-00@openssh.com 0
ssh_packet_process: Couldn't do anything with packet type 80
ssh_packet_channel_open_conf: Received a CHANNEL_OPEN_CONFIRMATION for channel 43:0
ssh_packet_channel_open_conf: Remote window : 0, maxpacket : 32768
channel_request: Channel request pty-req success
channel_rcv_change_window: Adding 2097152 bytes to channel (43:0) (from 0 bytes)
                                                                                grow_window: growing window (channel 43:0) to 12582912 bytes
                                                                                                                                            channel_request: Channel request shell success

**Comment by yury** [comment]
Can you post more verbose output? `ssh -vvvvvv host`

**Comment by Iguana9999phil** [comment]
I seem to be unable to select that much of the log on iOS without loosing parts of it. Any way to get the verbose output in a log?

**Comment by yury** [comment]
Yep `ssh -vvvvvvv host 2> log.txt` and then `pbcopy log.txt`

**Comment by Iguana9999phil** [comment]
ssh_connect: libssh 0.8.3 (c) 2003-2018 Aris Adamantiadis, Andreas Schneider and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
ssh_connect: Socket connecting, now waiting for the callbacks to work
ssh_connect: current state : 1
ssh_connect: current state : 1
ssh_connect: current state : 1
ssh_connect: current state : 1
ssh_connect: current state : 1
ssh_connect: current state : 1
ssh_connect: current state : 1
ssh_connect: current state : 1
-[IO stream:handleEvent:]: Received POLLOUT in connecting state
socket_callback_connected: Socket connection callback: 1 (0)
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
callback_receive_banner: Received banner: SSH-2.0-OpenSSH_7.6p1 Ubuntu-4
ssh_client_connection_callback: SSH server banner: SSH-2.0-OpenSSH_7.6p1 Ubuntu-4
ssh_analyze_banner: Analyzing banner: SSH-2.0-OpenSSH_7.6p1 Ubuntu-4
ssh_analyze_banner: We are talking to an OpenSSH client version: 7.6 (70600)
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_packet_socket_callback: packet: read type 20 [len=1076,padding=6,comp=1069,payload=1069]
ssh_packet_process: Dispatching handler for packet type 20
ssh_client_select_hostkeys: Changing host key method to "ssh-ed25519"
ssh_kex_select_methods: Negotiated curve25519-sha256,ssh-ed25519,aes256-ctr,aes256-ctr,hmac-sha2-256,hmac-sha2-256,zlib@openssh.com,zlib@openssh.com,,
packet_send2: packet: wrote [len=588,padding=6,comp=581,payload=581]
packet_send2: packet: wrote [len=44,padding=6,comp=37,payload=37]
ssh_connect: current state : 6
ssh_connect: current state : 6
ssh_connect: current state : 6
ssh_connect: current state : 6
ssh_packet_socket_callback: packet: read type 31 [len=188,padding=8,comp=179,payload=179]
ssh_packet_process: Dispatching handler for packet type 31
ssh_packet_dh_reply: Received SSH_KEXDH_REPLY
packet_send2: packet: wrote [len=12,padding=10,comp=1,payload=1]
ssh_client_curve25519_reply: SSH_MSG_NEWKEYS sent
ssh_packet_socket_callback: Processing 16 bytes left in socket buffer
ssh_packet_socket_callback: packet: read type 21 [len=12,padding=10,comp=1,payload=1]
ssh_packet_process: Dispatching handler for packet type 21
ssh_packet_newkeys: Received SSH_MSG_NEWKEYS
crypt_set_algorithms2: Set output algorithm to aes256-ctr
crypt_set_algorithms2: Set HMAC output algorithm to hmac-sha2-256
crypt_set_algorithms2: Set input algorithm to aes256-ctr
crypt_set_algorithms2: Set HMAC input algorithm to hmac-sha2-256
ssh_packet_newkeys: Signature verified and valid
ssh_connect: current state : 7
packet_send2: packet: wrote [len=28,padding=10,comp=17,payload=17]
ssh_service_request: Sent SSH_MSG_SERVICE_REQUEST (service ssh-userauth)
ssh_userauth_request_service: Failed to request "ssh-userauth" service
ssh_userauth_request_service: Failed to request "ssh-userauth" service
ssh_userauth_request_service: Failed to request "ssh-userauth" service
ssh_userauth_request_service: Failed to request "ssh-userauth" service
ssh_userauth_request_service: Failed to request "ssh-userauth" service
ssh_packet_socket_callback: packet: read type 6 [len=28,padding=10,comp=17,payload=17]
ssh_packet_process: Dispatching handler for packet type 6
ssh_packet_service_accept: Received SSH_MSG_SERVICE_ACCEPT
packet_send2: packet: wrote [len=44,padding=5,comp=38,payload=38]
ssh_packet_socket_callback: packet: read type 51 [len=44,padding=19,comp=24,payload=24]
ssh_packet_process: Dispatching handler for packet type 51
ssh_packet_userauth_failure: Access denied for 'none'. Authentication that can continue: publickey,password
ssh_packet_userauth_failure: Access denied for 'none'. Authentication that can continue: publickey,password
ssh_pki_import_privkey_base64: Trying to decode privkey passphrase=false
ssh_key_algorithm_allowed: Checking rsa-sha2-512 with list <ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa,rsa-sha2-512,rsa-sha2-256,ssh-dss>
ssh_key_algorithm_allowed: Checking rsa-sha2-256 with list <ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa,rsa-sha2-512,rsa-sha2-256,ssh-dss>
ssh_key_algorithm_allowed: Checking ssh-rsa with list <ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa,rsa-sha2-512,rsa-sha2-256,ssh-dss>
ssh_key_algorithm_allowed: Checking rsa-sha2-512 with list <ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa,rsa-sha2-512,rsa-sha2-256,ssh-dss>
ssh_key_algorithm_allowed: Checking rsa-sha2-256 with list <ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa,rsa-sha2-512,rsa-sha2-256,ssh-dss>
packet_send2: packet: wrote [len=1132,padding=6,comp=1125,payload=1125]
ssh_packet_socket_callback: packet: read type 52 [len=12,padding=10,comp=1,payload=1]
ssh_packet_process: Dispatching handler for packet type 52
ssh_packet_userauth_success: Authentication successful
ssh_packet_userauth_success: Enabling delayed compression OUT
ssh_packet_userauth_success: Enabling delayed compression IN
channel_open: Creating a channel 43 with 2097152 window and 32768 max packet
packet_send2: packet: wrote [len=44,padding=18,comp=25,payload=24]
channel_open: Sent a SSH_MSG_CHANNEL_OPEN type session for channel 43
ssh_packet_socket_callback: packet: read type 80 [len=492,padding=16,comp=475,payload=475]
ssh_packet_process: Dispatching handler for packet type 80
ssh_packet_global_request: Received SSH_MSG_GLOBAL_REQUEST packet
ssh_packet_global_request: UNKNOWN SSH_MSG_GLOBAL_REQUEST hostkeys-00@openssh.com 0
ssh_packet_process: Couldn't do anything with packet type 80
packet_send2: packet: wrote [len=12,padding=4,comp=7,payload=5]
ssh_packet_socket_callback: packet: read type 91 [len=28,padding=16,comp=11,payload=17]
ssh_packet_process: Dispatching handler for packet type 91
ssh_packet_channel_open_conf: Received SSH2_MSG_CHANNEL_OPEN_CONFIRMATION
ssh_packet_channel_open_conf: Received a CHANNEL_OPEN_CONFIRMATION for channel 43:0
ssh_packet_channel_open_conf: Remote window : 0, maxpacket : 32768
packet_send2: packet: wrote [len=60,padding=18,comp=41,payload=56]
channel_request: Sent a SSH_MSG_CHANNEL_REQUEST pty-req
ssh_packet_socket_callback: packet: read type 99 [len=12,padding=6,comp=5,payload=5]
ssh_packet_process: Dispatching handler for packet type 99
ssh_packet_channel_success: Received SSH_CHANNEL_SUCCESS on channel (43:0)
channel_request: Channel request pty-req success
packet_send2: packet: wrote [len=28,padding=15,comp=12,payload=15]
channel_request: Sent a SSH_MSG_CHANNEL_REQUEST shell
ssh_packet_socket_callback: packet: read type 93 [len=28,padding=18,comp=9,payload=9]
ssh_packet_process: Dispatching handler for packet type 93
channel_rcv_change_window: Adding 2097152 bytes to channel (43:0) (from 0 bytes)
ssh_packet_socket_callback: Processing 720 bytes left in socket buffer
ssh_packet_socket_callback: packet: read type 99 [len=12,padding=7,comp=4,payload=5]
ssh_packet_process: Dispatching handler for packet type 99
ssh_packet_channel_success: Received SSH_CHANNEL_SUCCESS on channel (43:0)
ssh_packet_socket_callback: Processing 672 bytes left in socket buffer
ssh_packet_socket_callback: packet: read type 94 [len=540,padding=6,comp=533,payload=1037]
ssh_packet_process: Dispatching handler for packet type 94
channel_rcv_data: Channel receiving 1028 bytes data in 0 (local win=2097152 remote win=2097152)
channel_default_bufferize: placing 1028 bytes into channel buffer (stderr=0)
channel_rcv_data: Channel windows are now (local win=2096124 remote win=2097152)
packet_send2: packet: wrote [len=28,padding=19,comp=8,payload=9]
grow_window: growing window (channel 43:0) to 12582912 bytes
ssh_packet_socket_callback: Processing 96 bytes left in socket buffer
ssh_packet_socket_callback: packet: read type 94 [len=60,padding=11,comp=48,payload=69]
ssh_packet_process: Dispatching handler for packet type 94
channel_rcv_data: Channel receiving 60 bytes data in 0 (local win=12582912 remote win=2097152)
channel_default_bufferize: placing 60 bytes into channel buffer (stderr=0)
channel_rcv_data: Channel windows are now (local win=12582852 remote win=2097152)
channel_request: Channel request shell success
packet_send2: packet: wrote [len=12,padding=4,comp=7,payload=10]
channel_write_common: channel_write wrote 1 bytes
ssh_packet_socket_callback: packet: read type 94 [len=12,padding=4,comp=7,payload=11]
ssh_packet_process: Dispatching handler for packet type 94
channel_rcv_data: Channel receiving 2 bytes data in 0 (local win=12582852 remote win=2097151)
channel_default_bufferize: placing 2 bytes into channel buffer (stderr=0)
channel_rcv_data: Channel windows are now (local win=12582850 remote win=2097151)
ssh_packet_socket_callback: Processing 48 bytes left in socket buffer
ssh_packet_socket_callback: packet: read type 94 [len=12,padding=6,comp=5,payload=69]
ssh_packet_process: Dispatching handler for packet type 94
channel_rcv_data: Channel receiving 60 bytes data in 0 (local win=12582850 remote win=2097151)
channel_default_bufferize: placing 60 bytes into channel buffer (stderr=0)
channel_rcv_data: Channel windows are now (local win=12582790 remote win=2097151)
packet_send2: packet: wrote [len=12,padding=6,comp=5,payload=10]
channel_write_common: channel_write wrote 1 bytes
packet_send2: packet: wrote [len=12,padding=6,comp=5,payload=10]
channel_write_common: channel_write wrote 1 bytes
packet_send2: packet: wrote [len=12,padding=6,comp=5,payload=10]
channel_write_common: channel_write wrote 1 bytes
ssh_packet_socket_callback: packet: read type 94 [len=12,padding=4,comp=7,payload=10]
ssh_packet_process: Dispatching handler for packet type 94
channel_rcv_data: Channel receiving 1 bytes data in 0 (local win=12582790 remote win=2097148)
channel_default_bufferize: placing 1 bytes into channel buffer (stderr=0)
channel_rcv_data: Channel windows are now (local win=12582789 remote win=2097148)
packet_send2: packet: wrote [len=12,padding=5,comp=6,payload=10]
channel_write_common: channel_write wrote 1 bytes
ssh_packet_socket_callback: packet: read type 94 [len=12,padding=6,comp=5,payload=10]
ssh_packet_process: Dispatching handler for packet type 94
channel_rcv_data: Channel receiving 1 bytes data in 0 (local win=12582789 remote win=2097147)
channel_default_bufferize: placing 1 bytes into channel buffer (stderr=0)
channel_rcv_data: Channel windows are now (local win=12582788 remote win=2097147)
ssh_packet_socket_callback: packet: read type 94 [len=12,padding=5,comp=6,payload=10]
ssh_packet_process: Dispatching handler for packet type 94
channel_rcv_data: Channel receiving 1 bytes data in 0 (local win=12582788 remote win=2097147)
channel_default_bufferize: placing 1 bytes into channel buffer (stderr=0)
channel_rcv_data: Channel windows are now (local win=12582787 remote win=2097147)
ssh_packet_socket_callback: packet: read type 94 [len=12,padding=6,comp=5,payload=10]
ssh_packet_process: Dispatching handler for packet type 94
channel_rcv_data: Channel receiving 1 bytes data in 0 (local win=12582787 remote win=2097147)
channel_default_bufferize: placing 1 bytes into channel buffer (stderr=0)
channel_rcv_data: Channel windows are now (local win=12582786 remote win=2097147)
packet_send2: packet: wrote [len=12,padding=6,comp=5,payload=10]
channel_write_common: channel_write wrote 1 bytes
packet_send2: packet: wrote [len=12,padding=6,comp=5,payload=10]
channel_write_common: channel_write wrote 1 bytes
packet_send2: packet: wrote [len=12,padding=6,comp=5,payload=10]
channel_write_common: channel_write wrote 1 bytes
ssh_packet_socket_callback: packet: read type 94 [len=12,padding=6,comp=5,payload=10]
ssh_packet_process: Dispatching handler for packet type 94
channel_rcv_data: Channel receiving 1 bytes data in 0 (local win=12582786 remote win=2097144)
channel_default_bufferize: placing 1 bytes into channel buffer (stderr=0)
channel_rcv_data: Channel windows are now (local win=12582785 remote win=2097144)
packet_send2: packet: wrote [len=12,padding=5,comp=6,payload=10]
channel_write_common: channel_write wrote 1 bytes
ssh_packet_socket_callback: packet: read type 94 [len=12,padding=6,comp=5,payload=10]
ssh_packet_process: Dispatching handler for packet type 94
channel_rcv_data: Channel receiving 1 bytes data in 0 (local win=12582785 remote win=2097143)
channel_default_bufferize: placing 1 bytes into channel buffer (stderr=0)
channel_rcv_data: Channel windows are now (local win=12582784 remote win=2097143)
ssh_packet_socket_callback: packet: read type 94 [len=12,padding=5,comp=6,payload=10]
ssh_packet_process: Dispatching handler for packet type 94
channel_rcv_data: Channel receiving 1 bytes data in 0 (local win=12582784 remote win=2097143)
channel_default_bufferize: placing 1 bytes into channel buffer (stderr=0)
channel_rcv_data: Channel windows are now (local win=12582783 remote win=2097143)
ssh_packet_socket_callback: packet: read type 94 [len=12,padding=5,comp=6,payload=11]
ssh_packet_process: Dispatching handler for packet type 94
channel_rcv_data: Channel receiving 2 bytes data in 0 (local win=12582783 remote win=2097143)
channel_default_bufferize: placing 2 bytes into channel buffer (stderr=0)
channel_rcv_data: Channel windows are now (local win=12582781 remote win=2097143)
packet_send2: packet: wrote [len=12,padding=6,comp=5,payload=10]
channel_write_common: channel_write wrote 1 bytes
packet_send2: packet: wrote [len=12,padding=7,comp=4,payload=10]
channel_write_common: channel_write wrote 1 bytes
ssh_packet_socket_callback: packet: read type 94 [len=28,padding=17,comp=10,payload=13]
ssh_packet_process: Dispatching handler for packet type 94
channel_rcv_data: Channel receiving 4 bytes data in 0 (local win=12582781 remote win=2097141)
channel_default_bufferize: placing 4 bytes into channel buffer (stderr=0)
channel_rcv_data: Channel windows are now (local win=12582777 remote win=2097141)
packet_send2: packet: wrote [len=12,padding=7,comp=4,payload=10]
channel_write_common: channel_write wrote 1 bytes
ssh_packet_socket_callback: packet: read type 94 [len=12,padding=7,comp=4,payload=13]
ssh_packet_process: Dispatching handler for packet type 94
channel_rcv_data: Channel receiving 4 bytes data in 0 (local win=12582777 remote win=2097140)
channel_default_bufferize: placing 4 bytes into channel buffer (stderr=0)
channel_rcv_data: Channel windows are now (local win=12582773 remote win=2097140)
packet_send2: packet: wrote [len=12,padding=6,comp=5,payload=10]
channel_write_common: channel_write wrote 1 bytes
packet_send2: packet: wrote [len=12,padding=7,comp=4,payload=10]
channel_write_common: channel_write wrote 1 bytes
ssh_packet_socket_callback: packet: read type 94 [len=12,padding=7,comp=4,payload=13]
ssh_packet_process: Dispatching handler for packet type 94
channel_rcv_data: Channel receiving 4 bytes data in 0 (local win=12582773 remote win=2097138)
channel_default_bufferize: placing 4 bytes into channel buffer (stderr=0)
channel_rcv_data: Channel windows are now (local win=12582769 remote win=2097138)
ssh_packet_socket_callback: packet: read type 94 [len=12,padding=6,comp=5,payload=13]
ssh_packet_process: Dispatching handler for packet type 94
channel_rcv_data: Channel receiving 4 bytes data in 0 (local win=12582769 remote win=2097138)
channel_default_bufferize: placing 4 bytes into channel buffer (stderr=0)
channel_rcv_data: Channel windows are now (local win=12582765 remote win=2097138)
ssh_packet_socket_callback: packet: read type 94 [len=12,padding=7,comp=4,payload=13]
ssh_packet_process: Dispatching handler for packet type 94
channel_rcv_data: Channel receiving 4 bytes data in 0 (local win=12582765 remote win=2097138)
channel_default_bufferize: placing 4 bytes into channel buffer (stderr=0)
channel_rcv_data: Channel windows are now (local win=12582761 remote win=2097138)
packet_send2: packet: wrote [len=12,padding=7,comp=4,payload=10]
channel_write_common: channel_write wrote 1 bytes
packet_send2: packet: wrote [len=12,padding=7,comp=4,payload=10]
channel_write_common: channel_write wrote 1 bytes
ssh_packet_socket_callback: packet: read type 94 [len=12,padding=7,comp=4,payload=13]
ssh_packet_process: Dispatching handler for packet type 94
channel_rcv_data: Channel receiving 4 bytes data in 0 (local win=12582761 remote win=2097136)
channel_default_bufferize: placing 4 bytes into channel buffer (stderr=0)
channel_rcv_data: Channel windows are now (local win=12582757 remote win=2097136)
packet_send2: packet: wrote [len=12,padding=6,comp=5,payload=10]
channel_write_common: channel_write wrote 1 bytes
ssh_packet_socket_callback: packet: read type 94 [len=12,padding=6,comp=5,payload=13]
ssh_packet_process: Dispatching handler for packet type 94
channel_rcv_data: Channel receiving 4 bytes data in 0 (local win=12582757 remote win=2097135)
channel_default_bufferize: placing 4 bytes into channel buffer (stderr=0)
channel_rcv_data: Channel windows are now (local win=12582753 remote win=2097135)
packet_send2: packet: wrote [len=12,padding=7,comp=4,payload=10]
channel_write_common: channel_write wrote 1 bytes
packet_send2: packet: wrote [len=12,padding=7,comp=4,payload=10]
channel_write_common: channel_write wrote 1 bytes
ssh_packet_socket_callback: packet: read type 94 [len=12,padding=7,comp=4,payload=13]
ssh_packet_process: Dispatching handler for packet type 94
channel_rcv_data: Channel receiving 4 bytes data in 0 (local win=12582753 remote win=2097133)
channel_default_bufferize: placing 4 bytes into channel buffer (stderr=0)
channel_rcv_data: Channel windows are now (local win=12582749 remote win=2097133)
packet_send2: packet: wrote [len=12,padding=7,comp=4,payload=10]
channel_write_common: channel_write wrote 1 bytes
ssh_packet_socket_callback: packet: read type 94 [len=12,padding=6,comp=5,payload=13]
ssh_packet_process: Dispatching handler for packet type 94
channel_rcv_data: Channel receiving 4 bytes data in 0 (local win=12582749 remote win=2097132)
channel_default_bufferize: placing 4 bytes into channel buffer (stderr=0)
channel_rcv_data: Channel windows are now (local win=12582745 remote win=2097132)
ssh_packet_socket_callback: packet: read type 94 [len=12,padding=6,comp=5,payload=10]
ssh_packet_process: Dispatching handler for packet type 94
channel_rcv_data: Channel receiving 1 bytes data in 0 (local win=12582745 remote win=2097132)
channel_default_bufferize: placing 1 bytes into channel buffer (stderr=0)
channel_rcv_data: Channel windows are now (local win=12582744 remote win=2097132)
packet_send2: packet: wrote [len=12,padding=5,comp=6,payload=10]
channel_write_common: channel_write wrote 1 bytes
ssh_packet_socket_callback: packet: read type 94 [len=12,padding=6,comp=5,payload=10]
ssh_packet_process: Dispatching handler for packet type 94
channel_rcv_data: Channel receiving 1 bytes data in 0 (local win=12582744 remote win=2097131)
channel_default_bufferize: placing 1 bytes into channel buffer (stderr=0)
channel_rcv_data: Channel windows are now (local win=12582743 remote win=2097131)
packet_send2: packet: wrote [len=12,padding=6,comp=5,payload=10]
channel_write_common: channel_write wrote 1 bytes
ssh_packet_socket_callback: packet: read type 94 [len=12,padding=6,comp=5,payload=10]
ssh_packet_process: Dispatching handler for packet type 94
channel_rcv_data: Channel receiving 1 bytes data in 0 (local win=12582743 remote win=2097130)
channel_default_bufferize: placing 1 bytes into channel buffer (stderr=0)
channel_rcv_data: Channel windows are now (local win=12582742 remote win=2097130)
packet_send2: packet: wrote [len=12,padding=6,comp=5,payload=10]
channel_write_common: channel_write wrote 1 bytes
packet_send2: packet: wrote [len=12,padding=6,comp=5,payload=10]
channel_write_common: channel_write wrote 1 bytes
ssh_packet_socket_callback: packet: read type 94 [len=12,padding=6,comp=5,payload=10]
ssh_packet_process: Dispatching handler for packet type 94
channel_rcv_data: Channel receiving 1 bytes data in 0 (local win=12582742 remote win=2097128)
channel_default_bufferize: placing 1 bytes into channel buffer (stderr=0)
channel_rcv_data: Channel windows are now (local win=12582741 remote win=2097128)
packet_send2: packet: wrote [len=12,padding=6,comp=5,payload=10]
channel_write_common: channel_write wrote 1 bytes
ssh_packet_socket_callback: packet: read type 94 [len=12,padding=6,comp=5,payload=10]
ssh_packet_process: Dispatching handler for packet type 94
channel_rcv_data: Channel receiving 1 bytes data in 0 (local win=12582741 remote win=2097127)
channel_default_bufferize: placing 1 bytes into channel buffer (stderr=0)
channel_rcv_data: Channel windows are now (local win=12582740 remote win=2097127)
ssh_packet_socket_callback: packet: read type 94 [len=12,padding=6,comp=5,payload=10]
ssh_packet_process: Dispatching handler for packet type 94
channel_rcv_data: Channel receiving 1 bytes data in 0 (local win=12582740 remote win=2097127)
channel_default_bufferize: placing 1 bytes into channel buffer (stderr=0)
channel_rcv_data: Channel windows are now (local win=12582739 remote win=2097127)
ssh_packet_socket_callback: packet: read type 94 [len=12,padding=6,comp=5,payload=11]
ssh_packet_process: Dispatching handler for packet type 94
channel_rcv_data: Channel receiving 2 bytes data in 0 (local win=12582739 remote win=2097127)
channel_default_bufferize: placing 2 bytes into channel buffer (stderr=0)
channel_rcv_data: Channel windows are now (local win=12582737 remote win=2097127)
ssh_packet_socket_callback: packet: read type 94 [len=28,padding=14,comp=13,payload=17]
ssh_packet_process: Dispatching handler for packet type 94
channel_rcv_data: Channel receiving 8 bytes data in 0 (local win=12582737 remote win=2097127)
channel_default_bufferize: placing 8 bytes into channel buffer (stderr=0)
channel_rcv_data: Channel windows are now (local win=12582729 remote win=2097127)
ssh_packet_socket_callback: packet: read type 98 [len=28,padding=8,comp=19,payload=25]
ssh_packet_process: Dispatching handler for packet type 98
channel_rcv_request: received exit-status 0
ssh_packet_socket_callback: Processing 96 bytes left in socket buffer
ssh_packet_socket_callback: packet: read type 96 [len=12,padding=5,comp=6,payload=5]
ssh_packet_process: Dispatching handler for packet type 96
channel_rcv_eof: Received eof on channel (43:0)
packet_send2: packet: wrote [len=12,padding=6,comp=5,payload=5]
ssh_channel_send_eof: Sent a EOF on client channel (43:0)
packet_send2: packet: wrote [len=12,padding=6,comp=5,payload=5]
ssh_channel_close: Sent a close on client channel (43:0)
ssh_packet_socket_callback: Processing 48 bytes left in socket buffer
ssh_packet_socket_callback: packet: read type 97 [len=12,padding=5,comp=6,payload=5]
ssh_packet_process: Dispatching handler for packet type 97
channel_rcv_close: Received close on channel (43:0)

**Comment by yury** [comment]
I want to be able to reproduce this.

What server are you running? 
Any special sshd_config settings?

**Comment by Iguana9999phil** [comment]
Server is running Ubuntu 18.04.1 LTS 

ssh -G gives this

_printaddress no
_printconfiguration yes
compression yes
compressionlevel 6
connectionattempts 1
connecttimeout 20
exitonforwardfailure no
forwardagent no
forwardx11 no
hostname [redacted]
identityfile id_rsa
identityfile id_dsa
identityfile id_ecdsa
identityfile id_ed25519
kbdinteractiveauthentication yes
loglevel info
numberofpasswordprompts 3
passwordauthentication yes
port 22
pubkeyauthentication yes
requesttty auto
serveralivecountmax 3
serveraliveinterval 0
stricthostkeychecking ask
tcpkeepalive yes
user [redacted]

Normally password auth is disabled but enabled it for testing. Got another server which is giving the same issues same settings and all are using the same key.

**Comment by yury** [comment]
imported key form blink to prompt2 and import it back. works.
still investigating..

**Comment by Iguana9999phil** [comment]
Even with using just password Auth it gives me errors when using ssh (or mosh)

**Comment by yury** [comment]
Trying to run  Ubuntu 18.04.1 LTS on digital ocean

**Comment by yury** [comment]
On Ubuntu 18.04.1 LTS everything ok too....
And actually, logs looks the same.
🤔

**Comment by yury** [comment]
Just incase we don't miss anything.. 

Please provide following info:

1. device model
2. iOS version
3. blink version (`help` command prints it)

**Comment by Iguana9999phil** [comment]
Yes, tested here with a hetzner cloud instance using the same ssh key (other servers are also hetzner) with a fresh one it works using the already added key. I tested with the root user first, after that created the normal user and transferred the ssh key to that one (as i did on the other server) still works. Both running 18.04.1 LTS, the other server run docker and OpenVPN. Both should be interfering with ssh I presume.

1. iPad Pro 10.5
2. iOS 12.1
3. V12.2.52. Nov 10 2018 (TF version)

**Comment by yury** [comment]
May be your server prints out smth special after login (welcome banner)?

**Comment by Iguana9999phil** [comment]
Just the normal stuff that Ubuntu 18.04.1 LTS displays when logging in, the test server did that also. 
Welcome to Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-34-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Mon Nov 12 20:02:04 +08 2018

  System load:                    0.12
  Usage of /home:                 72.0% of 417.46GB
  Memory usage:                   38%
  Swap usage:                     11%
  Processes:                      255
  Users logged in:                1
  IP address for enp3s0:          
  IP address for tun0:            
  IP address for docker0:         
  IP address for br-f5473137c294:

 * Canonical Livepatch is available for installation.
   - Reduce system reboots and improve kernel security. Activate at:
     https://ubuntu.com/livepatch

111 packages can be updated.
45 updates are security updates.


You have new mail.
Last login: Mon Nov 12 19:59:32 2018 from

I’ve removed Blink and redownloaded it, used ssh name@ipaddress and after asking me to trust the host and after asking my password it worked, after that I tested mosh, that also worked.  
I proceeded with importing my private key from prompt 2 and added that NEXT to the default id_rsa key (presume this is generated on install?) ssh name@ipaddress gave me password prompt and after entering my password it didn’t display the prompt again until I press enter key. Then I changed the default id_rsa with my own key (renamed it id_rsa) ssh name@ipaddress this time didn’t give me a password prompt but still hanged until I pressed the enter key.

**Comment by yury** [comment]
Could it be that your key has passphrase (empty one somehow?) 

if you run with `ssh -vv host` is stops right after `blink: import key id_rsa` (or may be couple of lines) ?

**Comment by Iguana9999phil** [comment]
Yes the key has an empty pass phrase. Even if its the key it doesn’t explain why ssh name@ipaddress doesn’t work. 

PS I’ve remove the welcome message using sudo chmod -x /etc/update-motd.d/* And the first time it worked, after that it hangs again.

Using ssh2 works in all cases, any way to let mosh use ssh2? I just want to use mosh.

**Comment by yury** [comment]
Sorry for issue and thank you for your time.
If you run `ssh -T host ls -la` is it get stuck too?

**Comment by Iguana9999phil** [comment]
Yes it also gets stuck

**Comment by yury** [comment]
hmm, and what if turn on password auth and run

`ssh -o pubkeyauthentication=no host`

**Comment by Iguana9999phil** [comment]
Nope still same problem. If its easier for you I can create a new users and give you the credentials to test.

**Comment by yury** [comment]
Oh, that would helps a lot. It is the only one blocker for release ;)
Thank you!

**Comment by Iguana9999phil** [comment]
Done, mail with info is sent. If you need a FQDN or something let me know.

**Comment by yury** [comment]
Can we also quickly chat at discord ?  https://discord.gg/YaKPaT

I'm connected with key and password without any issues :(
mosh works too

**Comment by yury** [comment]
Hi @Iguana9999phil.

I pushed build 53 to TF, can you test it. Is it any better for you?

**Comment by Iguana9999phil** [comment]
Any idea how to fix this? Can’t there be an option in the config to use the old ssh version (ssh2) so at least a mosh can be set up? I’m trying to run mosh on my server and connect manually but Blink just says “mosh session finished” 
Kind of frustrating as I bought the app in the AppStore due to the good reviews and can’t use it. Testing Mosh using Termius works but I don’t like subscription apps.

**Comment by Iguana9999phil** [comment]
Hi, removed the older version and downloaded the latest just to be sure. Still not working for me. SSH2 works without issue.

**Comment by yury** [comment]
Ok, will add option to mosh for ssh2 ;(

**Comment by Iguana9999phil** [comment]
Is there going to be another TF version with the latest commit?

**Comment by yury** [comment]
No TF version.
We have submitted on Friday, but got rejected. Trying again today.

**Comment by yury** [comment]
@Iguana9999phil actually I pushed build 57 to TF (App Store review can take longer then expected).

There is '-2' flag now for mosh.

Example:
`mosh -2 <host>`

**Comment by Iguana9999phil** [comment]
Downloaded, tested and works perfectly now using mosh -2!

**Comment by yury** [comment]
Thank you @Iguana9999phil for you time and patience.  I'm still trying to figure out what is going on with ssh.
