### ISSUE TITLE
Kex algorithm diffie-hellman-group16-sha512

### ISSUE THREAD

**Issue by vorband** [blinksh/blink#616]
Please add support for kex algorithm *diffie-hellman-group16-sha512*.
I happen to be blocked out of a server that sets the following ciphers in the sshd_config: 
```
ciphers aes256-ctr,chacha20-poly1305@openssh.com
macs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com
kexalgorithms diffie-hellman-group16-sha512
hostkeyalgorithms ssh-ed25519,ssh-rsa,ecdsa-sha2-nistp256
pubkeyacceptedkeytypes ssh-ed25519,ssh-rsa

```

Connecting gives me the following error:
```
ssh_kex_select_methods: kex error : no match for method kex algos: server [diffie-hellman-group16-sha512], client [curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1]
ssh_connect: current state : 9

```

A fix is greatly appreciated.

**Comment by yury** [comment]
Hi @vorband,

I'm glad to tell you that next release should support it. I can send you invite to TF version, so you can test it. 

Just send me email to yury.korolev@gmail.com

**Comment by yury** [comment]
Hi @vorband,

We have released v12.4 with libssh-0.8.6. Is it better for you? Can you please check it?

Thank you.

**Comment by vorband** [comment]
hi @yury, I am still getting `kex error : no match for method mac algo client->server: server [hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com], client [hmac-sha2-256,hmac-sha2-512,hmac-sha1]`

**Comment by vorband** [comment]
Don‘t worry, I have a workaround.

**Comment by derekbelrose** [comment]
Is there any update on when this will be released?  I have a couple servers that I need to connect to but I don’t have full control over.  


kex error : no match for method mac algo client->server: server [hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com], client [hmac-sha2-256,hmac-sha2-512,hmac-sha1]

**Comment by yury** [comment]
Sorry, no news yet. Need to report to libssh team.

**Comment by yury** [comment]
I got good news!

There is already PR (actually MR) [for that](https://gitlab.com/libssh/libssh-mirror/merge_requests/4).

Hope it will make in feb release.

**Comment by yury** [comment]
Another update. PR just landed into master. So it will be in February release.

**Comment by yury** [comment]
v12.7 is out! 

Please reopen if it is not working for you!

Thanks.

**Comment by derekbelrose** [comment]
Yury, this is working beautiful in my usecase.  Thank you for getting this working!

**Comment by vorband** [comment]
Same here. Thank you!

**Comment by yury** [comment]
Thank you!

All credits should go to [Dirkjan Bussink](https://gitlab.com/dbussink). He is the one who actually implemented that in [libssh](https://gitlab.com/libssh/libssh-mirror/commits/master).

**Comment by derekbelrose** [comment]
Actually, I’m still seeing this issue on one of my docker containers with 12.7:

blink> ssh -l root hassio.local

kex error : no match for method mac algo client->server: server [hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com], client [hmac-sha2-256,hmac-sha2-512,hmac-sha1]
blink> ssh -v -l root hassio.local 
socket_callback_connected: Socket connection callback: 1 (0)
ssh_client_connection_callback: SSH server banner: SSH-2.0-OpenSSH_7.7
ssh_analyze_banner: Analyzing banner: SSH-2.0-OpenSSH_7.7
ssh_analyze_banner: We are talking to an OpenSSH client version: 7.7 (70700)
ssh_known_hosts_read_entries: Failed to open the known_hosts file '/etc/ssh/ssh_known_hosts': No such file or directory
ssh_kex_select_methods: kex error : no match for method mac algo client->server: server [hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com], client [hmac-sha2-256,hmac-sha2-512,hmac-sha1]

kex error : no match for method mac algo client->server: server [hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com], client [hmac-sha2-256,hmac-sha2-512,hmac-sha1]

You should be able to recreate this by setting:

# Cryptography
# ===================
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com
KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512

in your sshd_config on a SSH server.

**Comment by yury** [comment]
Yep, my fault :(

Actual fix will be on libssh-0.9.x. So I leave this issue open  and will monitor libssh for release.

Sorry for false alarm.

And thank you for reproduce instructions.

**Comment by yury** [comment]
Fixed in v12.9. Feel free to reopen issue if needed.

```
ssh_key_algorithm_allowed: Checking rsa-sha2-512 with list <ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss>
ssh_key_algorithm_allowed: Checking rsa-sha2-512 with list <ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss>
```
