### ISSUE TITLE
Increasing freeze-ups lately

### ISSUE THREAD

**Issue by ejheil** [blinksh/blink#621]
Recently (in the past week or two) I've had it happen frequently that when I come back to the app from it being in the background, it will be unresponsive and often text which appeared while it was gone is partially missing.  Sometimes I will go open  anew session and work there, and eventually the first session will start working again, where it left off.

Not reproducible, so I'm only opening the issue so you're aware there's a general problem, even if it's not actionable.

**Comment by yury** [comment]
It should be fixed in 12.2. We already submitted this version for review.

**Comment by ejheil** [comment]
Thank you!

**Comment by linuxpng** [comment]
This still happens on 12.2 except now it will be a plain blank screen instead of the resumed image.  I am having the mosh sessions return to the blink prompt after resuming the app semi frequently as well.

**Comment by carloscabanero** [comment]
Hmmmm I haven't seen this myself on TestFlight and since the update. When is it happening to you?

**Comment by NightMachinary** [comment]
This is a regression, since I didn’t have this problem on version 27.

**Comment by linuxpng** [comment]
This is improved in 12.3.70 for the first terminal only.  Additional terminals are dropped to the blink shell, though the behavior has changed.  It will give you mosh help output as if you typed ‘mosh’ without a hostname.

**Comment by yury** [comment]
I think we can close this issue. Please reopen if you have any issues left.
