### ISSUE TITLE
No pipe ( | ) character with Danish Smart Keyboard

### ISSUE THREAD

**Issue by Regenuluz** [blinksh/blink#928]
I can't type the pipe character using the a danish smart keyboard.

The character is typed by pressing "option + i", however this key combination results in nothing being typed. 

iPad Pro 11"
iPadOS: 13.3
Blink: 13.2.1.210

**Comment by yury** [comment]
Hi @Regenuluz,

Can you log that with [KeyCodes](https://jsfiddle.net/yuryk/1vdmk8ws/embedded/result/) and post results here.

**Comment by Regenuluz** [comment]
@yury 


typed text:

    |

| n |        type |      code | key  |  kc | mods | repeat | l | comp |      iType | data |
|--:|------------:|----------:|:-----|----:|-----:|-------:|--:|-----:|-----------:|-----:|
| 1 |     keydown |  AltRight | Alt  |  18 |    A |        | 2 |      |            |      |
| 2 |     keydown |      KeyI | |    | 220 |    A |        | 0 |      |            |      |
| 3 | beforeinput |           |      |     |      |        |   |      | insertText |    | |
| 4 |       input |           |      |     |      |        |   |      | insertText |    | |
| 5 |       keyup |      KeyI | |    | 220 |    A |        | 0 |      |            |      |
| 6 |       keyup |  AltRight | Alt  |  18 |      |        | 2 |      |            |      |
| 7 |      change |           |      |     |      |        |   |      |            |      |

and


typed text:

    |

| n |        type |      code | key  |  kc | mods | repeat | l | comp |      iType | data |
|--:|------------:|----------:|:-----|----:|-----:|-------:|--:|-----:|-----------:|-----:|
| 1 |     keydown |   AltLeft | Alt  |  18 |    A |        | 1 |      |            |      |
| 2 |     keydown |      KeyI | |    | 220 |    A |        | 0 |      |            |      |
| 3 | beforeinput |           |      |     |      |        |   |      | insertText |    | |
| 4 |       input |           |      |     |      |        |   |      | insertText |    | |
| 5 |       keyup |      KeyI | |    | 220 |    A |        | 0 |      |            |      |
| 6 |       keyup |   AltLeft | Alt  |  18 |      |        | 1 |      |            |      |
| 7 |      change |           |      |     |      |        |   |      |            |      |

**Comment by yury** [comment]
Thank you. One more thing. Can you run local blink command `showkey` and type `|` in it. And send output here.

**Comment by yury** [comment]
It is very strange behavior. I will added `|` and `\` to custom presses as a workaround. So you can assign any combo to them.

Can I invite you to testflight? (send your apple id to yury.korolev@gmail.com)

**Comment by Regenuluz** [comment]
`showkey` doesn't give any output when pressing `option+i`. However `\` works just fine, the key combo for that on a danish keyboard is `option + shift + 7` which `showkey` displays as `\    92 0134 0x5c`.

**Comment by Regenuluz** [comment]
@yury I can't seem to find the pipe under custom presses in the testflight version. (13.2.1.210)

**Comment by yury** [comment]
@Regenuluz yep, you should wait for v13.3

**Comment by Regenuluz** [comment]
@yury Alright, just tested with 13.3.211 and setting the custom keypress for `|` as `option + i` but it is still not registering the keypress in the terminal.

**Comment by yury** [comment]
Can you share screenshot for that press?

**Comment by Regenuluz** [comment]
![FBC58B44-09F5-400D-A43A-34CC2FF2D65D](https://user-images.githubusercontent.com/1250227/73574749-c4fd8480-4476-11ea-904c-5cafad08ecff.png)
(Settings -> Keyboard -> Custom Presses)

Here you go.

**Comment by yury** [comment]
Thank you. Have no idea why it is not working yet. :(

**Comment by Regenuluz** [comment]
[Keyboard.ts#L143](https://github.com/blinksh/blink/blob/b496a8ba3434b2487c2da4e7ea1a4342e33e8f71/KB/JS/src/Keyboard.ts#L143) mentions that IOS reports the wrong keycodes with the control key pressed for e.g. `i`, I wonder if it's the same thing acting up here, though it does seem like the rest of the characters mentions act as they should. (I've only done a very short look around in the code base, so it's purely a guess.)

**Comment by yury** [comment]
That behavior with ctrl pressed. With alt I see it for the first time. Anyway, custom presses should trigger before they get processed by js in WKWebView.

**Comment by yury** [comment]
@Regenuluz can you gist your `.blink/kb.json` file?

**Comment by yury** [comment]
@Regenuluz I pushed v13.3.212 for you. Please take a look.

**Comment by Regenuluz** [comment]
It's still not working. :/ Here's a gist of the [kb.json](https://gist.github.com/Regenuluz/ce254a2e2f9a3ac592db31ad20beb47b) file on my iPad.

**Comment by Regenuluz** [comment]
So I just tested out a few more letters with the `option` key pressed, and Blink doesn't produce characters for either of `enui`. These should map to `éñü|` or at least that's the behavior when typing in `notes`. The rest of the characters seems to be correct.

**Comment by yury** [comment]
@Regenuluz, can you log them too with logger.
Also, can you try to reset KB settings and in option section turn off toggle ignore accents.

**Comment by Regenuluz** [comment]
@yury I reset the KB settings, but I'm not sure where to turn toggle ignore accents? However, now when testing with `showkey` it shows the following when pressing `option + i`:

```
^[    27 0033 0x1b
i       105 0151 0x69
```

**Comment by yury** [comment]
![4218C525-C892-4336-A520-D550FB2609D6](https://user-images.githubusercontent.com/5250/73595016-afdf2f00-4524-11ea-860f-1cf33fe3276a.jpeg)

**Comment by Regenuluz** [comment]
All right, progress!

When I turn off `ignore accents` and change the modifier from `Esc` to `Default` I get the correct behavior when I'm using the left `option` button, but not the right `option` button, even with `Same for both sides` toggled on BUT when I turn off `Same for both sides` and leave them identical I get the correct behavior for both right and left.

**Comment by yury** [comment]
Very good news! :)

Can you try that trick on build v13.2.1.210? Just to make I don't remove useful code. (Make sure to reset kb settings before)

Thank you again. I will fix ignore toggle for both sides.

**Comment by Regenuluz** [comment]
Yes I can, and it works like a charm on that build version too!
